import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { HeaderResponsive } from "@/components/Header";
import { FooterLinks } from "@/components/Footer";
import { Container } from "@mantine/core";
import { Hero } from "@/components/Hero";
import { FeaturesCards } from "@/components/FeatureCards";
import { ContactUs } from "@/components/ContactUs";
import { FaqWithBg } from "@/components/Faq";
import { Team } from "@/components/Team";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderResponsive
        links={[
          { label: "Home", link: "/" },
          { label: "About", link: "#" },
          { label: "Services", link: "#" },
          { label: "Contact", link: "#" },
        ]}
      />
      <main>
        <Hero />
        <Container size="xl" py={60}>
          <FeaturesCards />
          <Team
            members={[
              {
                name: "Arsalan",
                designation: "CEO",
                imgUrl: "/assets/img.jpg",
              },
            ]}
          />
        </Container>

        <FaqWithBg />
        <ContactUs />
      </main>
      <FooterLinks
        data={[
          {
            title: "About",
            links: [
              { label: "Home", link: "/" },
              { label: "About", link: "#" },
              { label: "Services", link: "#" },
              { label: "Contact", link: "#" },
            ],
          },
        ]}
      />
    </>
  );
}
